import type { Locale } from './i18n';

/**
 * Static interface strings. Content (dishes, articles, pages) lives in
 * src/content and is edited via the CMS; these are developer-owned labels.
 */
const strings = {
  'nav.primary': { en: 'Primary', th: 'หลัก', ru: 'Основная' },
  'nav.home': { en: 'Home', th: 'หน้าแรก', ru: 'Главная' },
  'nav.menu': { en: 'Menu', th: 'เมนู', ru: 'Меню' },
  'nav.about': { en: 'About us', th: 'เกี่ยวกับเรา', ru: 'О нас' },
  'nav.contact': { en: 'Contact & address', th: 'ติดต่อและที่อยู่', ru: 'Контакты и адрес' },
  'nav.blog': { en: 'Blog', th: 'บทความ', ru: 'Блог' },
  'nav.faq': { en: 'FAQ', th: 'คำถามที่พบบ่อย', ru: 'Вопросы и ответы' },
  'home.viewMenu': { en: 'View the menu', th: 'ดูเมนู', ru: 'Смотреть меню' },
  'home.orderGrab': { en: 'Order on GrabFood', th: 'สั่งผ่าน GrabFood', ru: 'Заказать в GrabFood' },
  'ordering.orderOn': {
    en: 'Order on {provider}',
    th: 'สั่งผ่าน {provider}',
    ru: 'Заказать через {provider}',
  },
  'ordering.deliveryOptions': {
    en: 'Delivery options',
    th: 'ช่องทางเดลิเวอรี',
    ru: 'Варианты доставки',
  },
  'ordering.deliveryAnswer': {
    en: 'Yes — via {providers}. Open a provider and enter your address for the live delivery area, fees and availability.',
    th: 'มีค่ะ ส่งผ่าน {providers} เปิดช่องทางที่ต้องการแล้วใส่ที่อยู่เพื่อดูพื้นที่ ค่าจัดส่ง และสถานะล่าสุด',
    ru: 'Да — через {providers}. Откройте нужный сервис и введите адрес: там показаны актуальные зона, стоимость и доступность доставки.',
  },
  'home.getDirections': { en: 'Get directions', th: 'นำทาง', ru: 'Как добраться' },
  'home.featured': { en: 'Featured dishes', th: 'เมนูแนะนำ', ru: 'Что попробовать' },
  'home.menuCount': { en: '{count} dishes', th: '{count} เมนู', ru: '{count} блюдо' },
  'home.menuCountNote': {
    en: 'Thai, Western, drinks',
    th: 'ไทย ตะวันตก เครื่องดื่ม',
    ru: 'тайское, европейское, напитки',
  },
  'home.openDailyNote': {
    en: 'Dine-in + delivery',
    th: 'นั่งทานที่ร้าน + เดลิเวอรี',
    ru: 'Зал + доставка',
  },
  'home.openDailyHint': {
    en: 'Dine-in hours + live delivery status',
    th: 'เวลานั่งทาน + สถานะเดลิเวอรีล่าสุด',
    ru: 'часы зала + актуальный статус доставки',
  },
  'home.happyCowNote': {
    en: 'Found by vegan travelers',
    th: 'นักเดินทางวีแกนหาเจอ',
    ru: 'находят vegan-туристы',
  },
  // {open} and {close} are replaced at render time from locations.json
  'home.openChip': {
    en: 'Dine-in {open}–{close} · delivery via {providers}',
    th: 'นั่งทาน {open}–{close} · เดลิเวอรีผ่าน {providers}',
    ru: 'Зал {open}–{close} · доставка через {providers}',
  },
  'home.openChipDineIn': {
    en: 'Dine-in {open}–{close}',
    th: 'นั่งทาน {open}–{close}',
    ru: 'Зал {open}–{close}',
  },
  'home.seeInMenu': { en: 'See in menu', th: 'ดูในเมนู', ru: 'Найти в меню' },
  'home.findUs': { en: 'Find us', th: 'มาหาเราได้ที่นี่', ru: 'Как нас найти' },
  'trust.jay': { en: '100% vegan', th: 'อาหารเจ 100%', ru: '100% веган' },
  'trust.family': { en: 'Family-run', th: 'ร้านครอบครัว', ru: 'Семейное кафе' },
  'trust.happycow': { en: 'HappyCow', th: 'HappyCow', ru: 'HappyCow' },
  'trust.honest': {
    en: 'No fish sauce, no egg, no dairy',
    th: 'ไม่ใส่น้ำปลา ไข่ นม',
    ru: 'Без рыбного соуса, яиц и молока',
  },
  'menu.title': {
    en: 'Vegan & jay menu in Pattaya',
    th: 'เมนูวีแกนและอาหารเจในพัทยา',
    ru: 'Веганское и джей-меню в Паттайе',
  },
  'menu.spicy': { en: 'spicy', th: 'เผ็ด', ru: 'острое' },
  'menu.categoriesNav': { en: 'Menu categories', th: 'หมวดเมนู', ru: 'Разделы меню' },
  'menu.contains': { en: 'Contains', th: 'มีส่วนผสม', ru: 'Содержит' },
  'menu.backToTop': { en: 'Back to top', th: 'กลับขึ้นบน', ru: 'Наверх' },
  'menu.orderGrab': {
    en: 'Order delivery on GrabFood',
    th: 'สั่งเดลิเวอรีผ่าน GrabFood',
    ru: 'Заказать доставку в GrabFood',
  },
  'menu.orderClosing': {
    en: 'Ready to order delivery? Choose an available provider.',
    th: 'พร้อมสั่งเดลิเวอรีแล้ว เลือกช่องทางที่เปิดให้บริการได้เลย',
    ru: 'Готовы заказать доставку? Выберите доступный сервис.',
  },
  'menu.quickPicks': {
    en: 'Popular on Grab',
    th: 'เมนูยอดนิยมบน Grab',
    ru: 'Популярно в Grab',
  },
  'menu.quickPicksHint': {
    en: 'Based on recent Grab orders.',
    th: 'อ้างอิงจากคำสั่งซื้อล่าสุดบน Grab',
    ru: 'По недавним заказам в Grab.',
  },
  'menu.viewDish': {
    en: 'View dish',
    th: 'ดูเมนูนี้',
    ru: 'К блюду',
  },
  'menu.catalogueSummary': {
    en: '{count} dishes · photos · prices in Thai baht',
    th: '{count} เมนู · มีรูป · ราคาเป็นบาท',
    ru: 'Позиций: {count} · фото · цены в батах',
  },
  'menu.catalogueImageNote': {
    en: 'Images from our Grab catalogue; actual presentation may vary.',
    th: 'ภาพจากแค็ตตาล็อก Grab ของร้าน การจัดเสิร์ฟจริงอาจแตกต่างกัน',
    ru: 'Изображения из каталога кафе в Grab; реальная подача может отличаться.',
  },
  'menu.plantNamesNote': {
    en: 'Chicken, pork, fish and egg in dish names always mean plant-based alternatives.',
    th: 'คำว่าไก่ หมู ปลา และไข่ในชื่อเมนู หมายถึงผลิตภัณฑ์จากพืชทั้งหมด',
    ru: '«Курица», «свинина», «рыба» и «яйцо» в названиях — всегда растительные аналоги.',
  },
  'menu.allVeganJay': {
    en: 'Every dish below is 100% vegan and jay.',
    th: 'ทุกเมนูด้านล่างเป็นวีแกนและอาหารเจ 100%',
    ru: 'Все блюда ниже — 100% веганские и джей.',
  },
  'menu.jayMeaningAction': {
    en: 'What does jay mean?',
    th: 'อาหารเจหมายถึงอะไร?',
    ru: 'Что означает «джей»?',
  },
  'menu.jayMeaning': {
    en: 'Jay (เจ) is a Thai food tradition stricter than vegetarian: it excludes animal ingredients and traditionally five pungent vegetables. It is not an allergen-safety guarantee.',
    th: 'อาหารเจเข้มงวดกว่ามังสวิรัติ: งดส่วนผสมจากสัตว์และตามธรรมเนียมงดผักฉุน 5 ชนิด แต่ไม่ได้รับรองว่าปลอดสารก่อภูมิแพ้',
    ru: 'Джей (เจ) — тайская традиция питания, более строгая, чем vegetarian: без животных ингредиентов и, по традиции, без пяти пахучих овощей. Это не гарантия безопасности при аллергии.',
  },
  'menu.photoOpen': {
    en: 'View a larger photo of {dish}',
    th: 'ดูรูป {dish} ขนาดใหญ่',
    ru: 'Открыть крупное фото блюда «{dish}»',
  },
  'menu.photoClose': {
    en: 'Close photo',
    th: 'ปิดรูป',
    ru: 'Закрыть фото',
  },
  'menu.searchLabel': {
    en: 'Find a dish',
    th: 'ค้นหาเมนู',
    ru: 'Найти блюдо',
  },
  'menu.searchPlaceholder': {
    en: 'Try pad thai, curry, smoothie…',
    th: 'เช่น ผัดไทย แกง สมูทตี้…',
    ru: 'Например: пад тай, карри, смузи…',
  },
  'menu.priceFilter': { en: 'Price', th: 'ราคา', ru: 'Цена' },
  'menu.priceUpTo150': { en: 'Up to ฿150', th: 'ไม่เกิน ฿150', ru: 'До ฿150' },
  'menu.priceNote': { en: 'Price note', th: 'หมายเหตุเรื่องราคา', ru: 'О ценах' },
  'menu.searchAction': { en: 'Search', th: 'ค้นหา', ru: 'Найти' },
  'menu.clearFilters': { en: 'Clear all', th: 'ล้างทั้งหมด', ru: 'Сбросить всё' },
  'menu.resultsCountOne': {
    en: '1 dish found',
    th: 'พบ 1 เมนู',
    ru: 'Найдено блюд: 1',
  },
  'menu.resultsCount': {
    en: '{count} dishes found',
    th: 'พบ {count} เมนู',
    ru: 'Найдено блюд: {count}',
  },
  'menu.noResults': {
    en: 'No dishes found. Try a shorter or different search.',
    th: 'ไม่พบเมนู ลองใช้คำค้นที่สั้นลงหรือคำอื่น',
    ru: 'Ничего не найдено. Попробуйте другой или более короткий запрос.',
  },
  'menu.noVerifiedResults': {
    en: 'No family-verified matches yet. Try removing a diet filter.',
    th: 'ยังไม่มีเมนูที่ครอบครัวตรวจสอบตรงกับตัวกรอง ลองยกเลิกตัวกรองอาหาร',
    ru: 'Пока нет блюд с подходящей семейной проверкой. Уберите диетический фильтр.',
  },
  'menu.showAllDishes': {
    en: 'Show all dishes',
    th: 'ดูเมนูทั้งหมด',
    ru: 'Показать все блюда',
  },
  'menu.dietFactsNote': {
    en: 'Diet notes appear only on family-checked dishes. For allergies, ask before ordering.',
    th: 'ข้อมูลอาหารจะแสดงเฉพาะเมนูที่ครอบครัวตรวจสอบแล้ว หากมีอาการแพ้ กรุณาสอบถามก่อนสั่ง',
    ru: 'Диетические отметки показываем только у блюд, проверенных семьёй. При аллергии уточните до заказа.',
  },
  'menu.dietGuidance': {
    en: 'Allergy & diet guidance',
    th: 'คำแนะนำเรื่องอาการแพ้และอาหาร',
    ru: 'Аллергии и особенности питания',
  },
  'menu.verifiedDietFilter': {
    en: 'Family-verified only',
    th: 'เฉพาะที่ครอบครัวตรวจสอบแล้ว',
    ru: 'Только проверенные семьёй',
  },
  'menu.notSpicy': { en: 'not spicy', th: 'ไม่เผ็ด', ru: 'не острое' },
  'menu.noGlutenIngredients': {
    en: 'no gluten ingredients',
    th: 'ไม่มีส่วนผสมที่มีกลูเตน',
    ru: 'без ингредиентов с глютеном',
  },
  'menu.jainRecipe': {
    en: 'Jain-friendly recipe',
    th: 'สูตรเหมาะกับผู้ทานเชน',
    ru: 'рецепт подходит для джайн',
  },
  'tag.vegan': { en: 'vegan', th: 'วีแกน', ru: 'веган' },
  'tag.vegetarian': { en: 'vegetarian', th: 'มังสวิรัติ', ru: 'вегетарианское' },
  'tag.jay': { en: 'jay', th: 'อาหารเจ', ru: 'джей' },
  'actions.quick': { en: 'Quick actions', th: 'เมนูลัด', ru: 'Быстрые действия' },
  'actions.call': { en: 'Call', th: 'โทร', ru: 'Звонок' },
  'actions.message': { en: 'Message', th: 'แชต', ru: 'Написать' },
  'actions.order': { en: 'Order', th: 'สั่ง', ru: 'Заказ' },
  'actions.map': { en: 'Map', th: 'แผนที่', ru: 'Карта' },
  'contact.callUs': { en: 'Call us', th: 'โทรหาเรา', ru: 'Позвоните нам' },
  'a11y.skipToContent': {
    en: 'Skip to content',
    th: 'ข้ามไปยังเนื้อหา',
    ru: 'Перейти к содержимому',
  },
  'notFound.text': {
    en: 'This page wandered off — maybe to the kitchen. The menu is ready, though.',
    th: 'ไม่พบหน้านี้ แต่เมนูของเรายังอยู่นะ',
    ru: 'Эта страница куда-то ушла. Зато меню на месте.',
  },
  'contact.hours': { en: 'Opening hours', th: 'เวลาเปิด-ปิด', ru: 'Часы работы' },
  'contact.address': { en: 'Address', th: 'ที่อยู่', ru: 'Адрес' },
  'contact.landmark': { en: 'Nearby landmark', th: 'จุดสังเกตใกล้ร้าน', ru: 'Ориентир рядом' },
  'contact.parking': { en: 'Parking', th: 'ที่จอดรถ', ru: 'Парковка' },
  'contact.arrivalNote': { en: 'Arrival tip', th: 'คำแนะนำการเดินทาง', ru: 'Как найти вход' },
  'contact.driverAddress': {
    en: 'Thai address for your driver',
    th: 'ที่อยู่ภาษาไทยสำหรับคนขับ',
    ru: 'Адрес на тайском для водителя',
  },
  'contact.phone': { en: 'Phone', th: 'โทร', ru: 'Телефон' },
  'contact.responseHours': {
    en: 'Messaging response hours',
    th: 'เวลาตอบข้อความ',
    ru: 'Когда отвечаем в мессенджерах',
  },
  'contact.closed': { en: 'Closed', th: 'ปิด', ru: 'Закрыто' },
  'contact.findUs': { en: 'Find us on the map', th: 'ดูแผนที่', ru: 'Мы на карте' },
  'contact.visitQuestions': {
    en: 'Answers about payment, allergens and delivery',
    th: 'ข้อมูลการชำระเงิน สารก่อภูมิแพ้ และเดลิเวอรี',
    ru: 'Оплата, аллергены и доставка',
  },
  'contact.visitQuestionsWithoutPayment': {
    en: 'Answers about allergens and delivery',
    th: 'ข้อมูลสารก่อภูมิแพ้และเดลิเวอรี',
    ru: 'Аллергены и доставка',
  },
  'contact.nightOrders': {
    en: 'Planning to visit? Use dine-in hours. Check current delivery availability in the provider app.',
    th: 'จะมาที่ร้านให้ดูเวลานั่งทาน ส่วนสถานะเดลิเวอรีล่าสุดดูได้ในแอปของผู้ให้บริการ',
    ru: 'В кафе ориентируйтесь на часы зала. Актуальную доступность доставки смотрите в приложении сервиса.',
  },
  'blog.readMore': { en: 'Read more', th: 'อ่านต่อ', ru: 'Читать далее' },
  'footer.reviews': { en: 'Leave us a review', th: 'รีวิวร้านเรา', ru: 'Оставить отзыв' },
  'trust.googleProfile': {
    en: 'Google Business Profile',
    th: 'โปรไฟล์ธุรกิจบน Google',
    ru: 'Профиль в Google',
  },
  'trust.tripadvisor': { en: 'Tripadvisor', th: 'Tripadvisor', ru: 'Tripadvisor' },
  'operations.payment': { en: 'Payment', th: 'การชำระเงิน', ru: 'Оплата' },
  'operations.paymentConfirmed': {
    en: 'Confirmed payment methods',
    th: 'ช่องทางชำระเงินที่ยืนยันแล้ว',
    ru: 'Подтверждённые способы оплаты',
  },
  'operations.payment.cash': { en: 'Cash', th: 'เงินสด', ru: 'Наличные' },
  'operations.payment.thai-qr': { en: 'Thai QR', th: 'Thai QR', ru: 'Thai QR' },
  'operations.payment.bank-transfer': {
    en: 'Bank transfer',
    th: 'โอนเงินผ่านธนาคาร',
    ru: 'Банковский перевод',
  },
  'operations.payment.card': { en: 'Card', th: 'บัตร', ru: 'Карта' },
  'operations.pricePolicy.unknown': {
    en: 'Website prices are a guide. Confirm the final price in the channel where you order.',
    th: 'ราคาบนเว็บไซต์ใช้เป็นข้อมูลเบื้องต้น กรุณาตรวจสอบราคาสุดท้ายในช่องทางที่สั่ง',
    ru: 'Цены на сайте служат ориентиром. Итоговую цену уточняйте в выбранном канале заказа.',
  },
  'operations.pricePolicy.same_everywhere': {
    en: 'The family confirms that website item prices are the same at the cafe and on active online ordering channels.',
    th: 'ครอบครัวยืนยันว่าราคาอาหารบนเว็บไซต์เท่ากับราคาที่ร้านและช่องทางสั่งออนไลน์ที่ใช้งานอยู่',
    ru: 'Семья подтвердила: цены блюд на сайте одинаковы в кафе и в активных онлайн-каналах заказа.',
  },
  'operations.pricePolicy.website_matches_counter': {
    en: 'Website prices match prices at the cafe; delivery prices and fees may differ.',
    th: 'ราคาบนเว็บไซต์ตรงกับราคาหน้าร้าน ส่วนราคาเดลิเวอรีและค่าธรรมเนียมอาจต่างกัน',
    ru: 'Цены сайта совпадают с ценами в кафе; цены доставки и сборы могут отличаться.',
  },
  'operations.pricePolicy.website_matches_grab': {
    en: 'Website item prices match GrabFood; prices at the cafe may differ.',
    th: 'ราคาอาหารบนเว็บไซต์ตรงกับ GrabFood ส่วนราคาที่ร้านอาจต่างกัน',
    ru: 'Цены блюд на сайте совпадают с GrabFood; цены в кафе могут отличаться.',
  },
  'operations.pricePolicy.channels_differ': {
    en: 'Prices differ by channel. Confirm the final item price and any fees where you order.',
    th: 'ราคาแตกต่างกันตามช่องทาง กรุณาตรวจสอบราคาและค่าธรรมเนียมในช่องทางที่สั่ง',
    ru: 'Цены различаются по каналам. Проверяйте итоговую цену и сборы там, где заказываете.',
  },
  'operations.channel.phone': { en: 'phone', th: 'โทรศัพท์', ru: 'телефон' },
  'operations.dietaryPrompt': {
    en: 'Questions about ingredients? Ask us before ordering.',
    th: 'มีคำถามเกี่ยวกับส่วนผสม? สอบถามเราก่อนสั่งอาหาร',
    ru: 'Есть вопросы о составе? Уточните до заказа.',
  },
  'operations.dietaryAsk': {
    en: 'Ask on {channel}',
    th: 'สอบถามทาง {channel}',
    ru: 'Спросить в {channel}',
  },
  'operations.dietaryAskPhone': {
    en: 'Call about ingredients',
    th: 'สอบถามทางโทรศัพท์',
    ru: 'Спросить по телефону',
  },
  'operations.dietaryLimit': {
    en: 'We can explain ingredients, but this is not an allergen-free guarantee.',
    th: 'เราช่วยอธิบายส่วนผสมได้ แต่ไม่ใช่การรับรองว่าปลอดสารก่อภูมิแพ้',
    ru: 'Мы можем уточнить состав, но это не гарантия отсутствия аллергенов.',
  },
  'operations.spiceQuestion': {
    en: 'Can I choose the spice level?',
    th: 'เลือกระดับความเผ็ดได้ไหม?',
    ru: 'Можно выбрать уровень остроты?',
  },
  'operations.spiceOffered': {
    en: 'Confirmed spice requests: {levels}. They apply only in the cases described below; ask before ordering.',
    th: 'ระดับความเผ็ดที่ครัวยืนยันว่าขอได้: {levels} ใช้ได้เฉพาะตามรายละเอียดด้านล่าง กรุณาสอบถามก่อนสั่งอาหาร',
    ru: 'Подтверждённые варианты остроты по запросу: {levels}. Они доступны только в указанных ниже случаях; уточните до заказа.',
  },
  'operations.spiceNotOffered': {
    en: 'The kitchen serves each dish at its standard spice level and does not offer a general spice-level adjustment.',
    th: 'ครัวเสิร์ฟแต่ละเมนูตามสูตรและไม่รับปรับระดับความเผ็ด',
    ru: 'Кухня готовит блюда со стандартной остротой и не меняет её по просьбе.',
  },
  'operations.spiceLevel.not-spicy': {
    en: 'not spicy',
    th: 'ไม่เผ็ด',
    ru: 'не остро',
  },
  'operations.spiceLevel.mild': { en: 'mild', th: 'เผ็ดน้อย', ru: 'слабо' },
  'operations.spiceLevel.medium': { en: 'medium', th: 'เผ็ดกลาง', ru: 'средне' },
  'operations.spiceLevel.hot': { en: 'hot', th: 'เผ็ดมาก', ru: 'остро' },
  'operations.pickup': { en: 'Pickup', th: 'รับอาหารที่ร้าน', ru: 'Самовывоз' },
  'operations.pickupAvailable': {
    en: 'Pickup is available',
    th: 'มีบริการรับอาหารที่ร้าน',
    ru: 'Самовывоз доступен',
  },
  'operations.pickupQuestion': {
    en: 'Can I order for pickup?',
    th: 'สั่งแล้วมารับที่ร้านได้ไหม?',
    ru: 'Можно заказать самовывоз?',
  },
  'operations.reservations': { en: 'Reservations', th: 'การจองโต๊ะ', ru: 'Бронирование' },
  'operations.reservationQuestion': {
    en: 'Can I reserve a table?',
    th: 'จองโต๊ะได้ไหม?',
    ru: 'Можно забронировать стол?',
  },
  'operations.reservationNotAccepted': {
    en: 'We do not take reservations. Please visit during dine-in hours.',
    th: 'ร้านไม่รับจองโต๊ะ กรุณาเข้ามาในเวลาเปิดหน้าร้าน',
    ru: 'Мы не принимаем бронирования. Приходите в часы работы зала.',
  },
  'operations.reservationAccepted': {
    en: 'Reservations are accepted. Contact us to request a table.',
    th: 'ร้านรับจองโต๊ะ กรุณาติดต่อเราเพื่อส่งคำขอจอง',
    ru: 'Бронирование доступно. Свяжитесь с нами, чтобы запросить стол.',
  },
  'operations.reservationLargeGroups': {
    en: 'Reservations are available for groups of {count} or more.',
    th: 'รับจองสำหรับกลุ่มตั้งแต่ {count} คนขึ้นไป',
    ru: 'Бронирование доступно для групп от {count} человек.',
  },
  'operations.reservationRequest': {
    en: 'Ask about a reservation',
    th: 'สอบถามเรื่องจองโต๊ะ',
    ru: 'Уточнить бронирование',
  },
  'media.illustrative': {
    en: 'Illustrative image — real cafe photos coming soon',
    th: 'ภาพประกอบ — ภาพจริงของร้านจะเพิ่มเร็ว ๆ นี้',
    ru: 'Иллюстрация — реальные фото кафе появятся позже',
  },
  'media.credit': { en: 'Photo', th: 'ภาพ', ru: 'Фото' },
  'lang.switch': { en: 'Language', th: 'ภาษา', ru: 'Язык' },
  'notFound.title': { en: 'Page not found', th: 'ไม่พบหน้านี้', ru: 'Страница не найдена' },
  'notFound.back': { en: 'Back to the home page', th: 'กลับหน้าแรก', ru: 'Вернуться на главную' },
  'days.mon': { en: 'Mon', th: 'จ.', ru: 'Пн' },
  'days.tue': { en: 'Tue', th: 'อ.', ru: 'Вт' },
  'days.wed': { en: 'Wed', th: 'พ.', ru: 'Ср' },
  'days.thu': { en: 'Thu', th: 'พฤ.', ru: 'Чт' },
  'days.fri': { en: 'Fri', th: 'ศ.', ru: 'Пт' },
  'days.sat': { en: 'Sat', th: 'ส.', ru: 'Сб' },
  'days.sun': { en: 'Sun', th: 'อา.', ru: 'Вс' },
  'days.daily': { en: 'Every day', th: 'ทุกวัน', ru: 'Ежедневно' },
  'hours.cafe': {
    en: 'Cafe',
    th: 'หน้าร้าน',
    ru: 'Кафе',
  },
  'hours.delivery': {
    en: 'Delivery',
    th: 'เดลิเวอรี',
    ru: 'Доставка',
  },
  'hours.deliveryValue': {
    en: 'Check live status in the app',
    th: 'ดูสถานะล่าสุดในแอป',
    ru: 'актуальный статус — в приложении',
  },
  'hours.deliveryLive': {
    en: 'Check live status in the app',
    th: 'ดูสถานะล่าสุดในแอป',
    ru: 'актуальный статус — в приложении',
  },
  'hours.specialOpen': {
    en: 'Special hours today: {open}–{close}',
    th: 'เวลาพิเศษวันนี้: {open}–{close}',
    ru: 'Сегодня особые часы: {open}–{close}',
  },
  'hours.specialClosed': {
    en: 'The cafe is closed today',
    th: 'วันนี้หน้าร้านปิด',
    ru: 'Сегодня кафе закрыто',
  },
  'hours.specialOpenOn': {
    en: 'Special hours on {date}: {open}–{close}',
    th: 'เวลาพิเศษวันที่ {date}: {open}–{close}',
    ru: 'Особые часы {date}: {open}–{close}',
  },
  'hours.specialClosedOn': {
    en: 'The cafe is closed on {date}',
    th: 'หน้าร้านปิดวันที่ {date}',
    ru: 'Кафе закрыто {date}',
  },
} satisfies Record<string, Record<Locale, string>>;

export type UiKey = keyof typeof strings;

export function t(locale: Locale, key: UiKey): string {
  return strings[key][locale];
}
